#!/bin/sh
### BEGIN INIT INFO
# Provides:          hostname
# Required-Start:
# Required-Stop:
# Default-Start:     S
# Default-Stop:
# Short-Description: Init TRIK-specific features 
run_init_scripts() {
 local dir
 dir=/usr/share/trik/init.d
[ -d $dir ] && for file in `ls $dir`; do . $dir/$file ; done 
}

run_init_scripts

