#!/bin/sh
### BEGIN INIT INFO
# Provides:         init-trik
# Required-Start:
# Required-Stop:
# Default-Start:     S
# Default-Stop:
# Short-Description: Init TRIK-specific features 
run_init_scripts() {
 dir=/usr/share/trik/init.d
[ -d $dir ] && for file in $dir/* ; do echo "Running $file" ; . $file ; done
}

run_init_scripts

