#!/bin/sh

### BEGIN INIT INFO
# Provides:          app
# Required-Start:    
# Required-Stop:     
# Should-Start:      
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: trik gamepad service
### END INIT INFO

DEFAULT_SERVICE_NAME=gamepad-service

CURRENT_SERVICE_NAME=current-gamepad-service
CURRENT_SERVICE_PATH=/etc/trik/$CURRENT_SERVICE_NAME

SERVICE_NAME=$(basename $0)
#back compatibility name parsing
[ $SERVICE_NAME==*.sh ] && SERVICE_NAME=${SERVICE_NAME%.*}
SERVICE_PATH=/etc/init.d/$SERVICE_NAME

SERVICE_PID=/var/run/$SERVICE_NAME.pid
SERVICE_LOG=/var/log/$SERVICE_NAME.log
SERVICE_CMD=status

UTILITY_NAME=nc
UTILITY_PATH=$UTILITY_NAME

#Additional vars
GAMEPAD_FIFO_NAME=$SERVICE_NAME.out.fifo
GAMEPAD_FIFO_PATH=/run/$GAMEPAD_FIFO_NAME #/var ?
GAMEPAD_PORT=4444

VERBOSE=1
log() {
  if [[ $2 -le $VERBOSE ]] ; then
    printf "$SERVICE_NAME: $1\n"
  fi
}


start() {
  echo -e "#!/bin/sh\n $SERVICE_PATH do_start" >$CURRENT_SERVICE_PATH
  killall -g $CURRENT_SERVICE_NAME
}


do_start() {
  test -p $GAMEPAD_FIFO_PATH || { rm -f $GAMEPAD_FIFO_PATH ; mkfifo $GAMEPAD_FIFO_PATH ; }
  $UTILITY_NAME -vlp $GAMEPAD_PORT | tee $GAMEPAD_FIFO_PATH &
  wait
}


stop() {
  echo -e "#!/bin/sh\n $SERVICE_PATH do_stop" > $CURRENT_SERVICE_PATH
  killall -g $CURRENT_SERVICE_NAME
}


do_stop() {
  sleep 600 &
  wait
}


restart() {
  stop
  start
}


parse_params() {
  while [[ $# > 0 ]]
  do
    key="$1"
    case $key in
      -v|--verbose)
        VERBOSE=$2
        shift
        ;;
      start|stop|restart|do_stop|do_start|status)
        SERVICE_CMD=$key
        shift
        ;;
      *)
        log "unknown option: $key" 0
        exit 1
        ;;
    esac
    shift
  done
  log "params parsed" 2
}


do_cmd() {
  case $SERVICE_CMD in
    start)
      start
      log "$SERVICE_NAME started" 1
      ;;
    do_start)
      do_start
      ;;
    stop)
      stop
      log "$SERVICE_NAME stopped" 1
      ;;
    do_stop)
      do_stop
      ;;
    restart)
      restart
      log "$SERVICE_NAME restarted" 1
      ;;
    status)
      status $SERVICE_PATH
      exit $?
      ;;
    *)
      echo "Usage: $SERVICE_NAME <flags> {start|stop|restart|status}" 0
      exit 1
  esac
}


#. /etc/init.d/functions
parse_params $@
do_cmd
